# Generated by Django 2.1.1 on 2018-11-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcudeInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acude_institucion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ayuda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consejero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consejero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LenguaIndigena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lengua_indigena',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('s', models.CharField(blank=True, max_length=4096, null=True)),
                ('o', models.CharField(blank=True, max_length=4096, null=True)),
                ('a', models.CharField(blank=True, max_length=4096, null=True)),
                ('p', models.CharField(blank=True, max_length=4096, null=True)),
                ('posible_solucion', models.CharField(blank=True, max_length=4096, null=True)),
                ('consejero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Consejero')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.AcudeInstitucion')),
            ],
            options={
                'db_table': 'llamada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LLamadaAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Ayuda')),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada')),
            ],
            options={
                'db_table': 'llamada_ayuda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedioContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medio_contacto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModalidadViolencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modalidad_violencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Estado')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NivelEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel_estudio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NivelViolencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel_violencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocupacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'religion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_ayuda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_caso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoViolencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_violencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('telefono', models.CharField(blank=True, max_length=256, null=True)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstadoCivil')),
                ('lengua_indigena', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.LenguaIndigena')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Municipio')),
                ('nivel_estudio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.NivelEstudio')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Ocupacion')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Religion')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Sexo')),
            ],
            options={
                'db_table': 'victima',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Violentometro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'violentometro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ViveCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vive_con',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='victima',
            name='vive_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.ViveCon'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='medio_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.MedioContacto'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='tipo_caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoCaso'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='tipo_violencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoViolencia'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='victima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Victima'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='violentometro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Violentometro'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Pais'),
        ),
        migrations.AddField(
            model_name='ayuda',
            name='tipo_ayuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoAyuda'),
        ),
    ]
