# Generated by Django 2.1.1 on 2018-11-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('correo', models.EmailField(max_length=128, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('a_paterno', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('fecha_nac', models.DateField()),
                ('estatus', models.BooleanField(default=False)),
                ('foto', models.FileField(blank=True, db_column='foto', null=True, upload_to='usuarios/')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Sexo')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolHasPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Permission')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Rol')),
            ],
            options={
                'db_table': 'rol_has_permissions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(through='config.RolHasPermissions', to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(to='config.Rol'),
        ),
    ]
