# Generated by Django 2.1.1 on 2018-11-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20181126_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Rol'),
            preserve_default=False,
        ),
    ]
