# Generated by Django 2.1.1 on 2018-11-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_llamada_consejero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consejero',
        ),
    ]
