# Generated by Django 2.1.1 on 2018-11-27 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_delete_consejero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejero',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoUsuario')),
            ],
            options={
                'db_table': 'consejero',
                'managed': True,
            },
            bases=('config.usuario',),
        ),
    ]
