# Generated by Django 2.1.1 on 2018-11-27 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_consejero'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='consejero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Consejero'),
            preserve_default=False,
        ),
    ]
