# Generated by Django 2.1.1 on 2018-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_llamada_consejero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
