# Generated by Django 2.1.1 on 2018-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_usuario_a_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(db_column='foto', default='usuarios/usuario-generico.jpg', upload_to='usuarios/'),
            preserve_default=False,
        ),
    ]
