# Generated by Django 2.1.1 on 2018-12-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20181128_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusLLamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estatus_llamada',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='llamada',
            name='vida_en_riesgo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llamada',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusLLamada'),
        ),
    ]
