# Generated by Django 2.1.1 on 2019-01-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20190113_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='victima',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='victima',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='victima',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='lengua_indigena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.LenguaIndigena'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Municipio'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='nivel_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.NivelEstudio'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='nombre',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='victima',
            name='ocupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Ocupacion'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Religion'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Sexo'),
        ),
        migrations.AlterField(
            model_name='victima',
            name='telefono',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='victima',
            name='vive_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.ViveCon'),
        ),
    ]
