# Generated by Django 2.1.1 on 2019-01-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20190115_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.MotivoLLamada'),
        ),
    ]
