# Generated by Django 2.1.1 on 2019-01-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20190115_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusLLamada'),
        ),
    ]
