# Generated by Django 2.1.1 on 2019-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20190116_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estado_mental',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nivel_de_riesgo',
                'managed': True,
            },
        ),
    ]
