# Generated by Django 2.1.1 on 2019-01-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_estadomental_nivelriesgo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llamada',
            old_name='p',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='llamada',
            old_name='s',
            new_name='f',
        ),
    ]
