# Generated by Django 2.1.1 on 2019-01-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20190116_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='estado_mental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstadoMental'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llamada',
            name='nivel_riesgo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.NivelRiesgo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llamada',
            name='vive_con',
            field=models.ManyToManyField(to='config.ViveCon'),
        ),
    ]
