# Generated by Django 2.1.1 on 2019-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_auto_20190116_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='tipo_ayuda',
            field=models.TextField(default=' ', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llamada',
            name='tipo_caso',
            field=models.TextField(default=' ', max_length=1024),
            preserve_default=False,
        ),
    ]
