# Generated by Django 2.1.1 on 2019-01-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_auto_20190117_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriatipificacion',
            name='tipificacion',
        ),
        migrations.RemoveField(
            model_name='tipicifacionllamada',
            name='categoria_tipificacion',
        ),
        migrations.DeleteModel(
            name='CategoriaTipificacion',
        ),
        migrations.DeleteModel(
            name='TipicifacionLLamada',
        ),
    ]
