# Generated by Django 2.1.1 on 2019-01-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_categoriatipificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipicifacionLLamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=512)),
                ('categoria_tipificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.CategoriaTipificacion')),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada')),
            ],
            options={
                'db_table': 'tipificacion_llamada',
                'managed': True,
            },
        ),
    ]
