# Generated by Django 2.1.1 on 2019-01-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_tipicifacionllamada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipicifacionLLamada',
            new_name='TipificacionLLamada',
        ),
    ]
