# Generated by Django 2.1.1 on 2019-01-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_auto_20190117_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamada',
            name='vive_con',
        ),
    ]
