# Generated by Django 2.1.1 on 2019-01-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_remove_llamada_vive_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='estado_mental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstadoMental'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='nivel_riesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.NivelRiesgo'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='tipo_ayuda',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='tipo_caso',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
