# Generated by Django 2.1.1 on 2019-01-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_llamada_causa_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='victima',
            name='redes_apoyo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.RedesApoyo'),
        ),
    ]
