# Generated by Django 2.1.1 on 2019-01-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_auto_20190128_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_rubro', models.BooleanField(default=False)),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada')),
            ],
            options={
                'managed': True,
                'db_table': 'calificacion_llamada',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'evaluacion_servicio',
            },
        ),
        migrations.AddField(
            model_name='calificacionllamada',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Evaluacion'),
        ),
    ]
