# Generated by Django 2.1.1 on 2019-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_auto_20190129_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='calificada',
            field=models.BooleanField(default=False),
        ),
    ]
