# Generated by Django 2.1.1 on 2019-01-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_llamada_calificada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='valor',
        ),
    ]
