# Generated by Django 2.1.1 on 2019-02-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_remove_evaluacion_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamada',
            name='calificada',
        ),
        migrations.AddField(
            model_name='llamada',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
