# Generated by Django 2.1.1 on 2019-02-04 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_auto_20190131_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaLLamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
                'db_table': 'tarea_llamada',
            },
        ),
        migrations.RemoveField(
            model_name='comoseentero',
            name='medio',
        ),
        migrations.AddField(
            model_name='llamada',
            name='agresor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Agresor'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='como_se_entero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.ComoSeEntero'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='fase_violencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.FaseViolencia'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='modalidad_violencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.ModalidadViolencia'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='semaforo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Semaforo'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='victima_involucrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.VictimaInvolucrada'),
        ),
        migrations.DeleteModel(
            name='MedioComunicacion',
        ),
        migrations.AddField(
            model_name='llamada',
            name='tareas',
            field=models.ManyToManyField(related_name='tareas', to='config.TareaLLamada'),
        ),
    ]
