# Generated by Django 2.1.1 on 2019-02-05 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0042_auto_20190203_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='adjuntos/')),
            ],
            options={
                'db_table': 'archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.CharField(max_length=500)),
                ('archivos', models.ManyToManyField(to='config.Archivo')),
                ('destinatarios', models.ManyToManyField(related_name='recibidos', related_query_name='recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuerpo', models.CharField(max_length=500)),
                ('destinatarios', models.ManyToManyField(related_name='recados', related_query_name='recados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recado',
                'managed': True,
            },
        ),
    ]
