# Generated by Django 2.1.1 on 2019-02-07 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_archivo_mensaje_recado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=3000)),
            ],
            options={
                'managed': True,
                'db_table': 'comentario_llamada',
            },
        ),
        migrations.CreateModel(
            name='CompromisoLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
            ],
            options={
                'managed': True,
                'db_table': 'compromiso_llamada',
            },
        ),
        migrations.AddField(
            model_name='comentariollamada',
            name='compromisos',
            field=models.ManyToManyField(related_name='compromisos', related_query_name='compromisos', to='config.CompromisoLlamada'),
        ),
        migrations.AddField(
            model_name='comentariollamada',
            name='llamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada'),
        ),
    ]
