# Generated by Django 2.1.1 on 2019-02-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0044_auto_20190206_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estatus_usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='estatus_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='config.EstatusUsuario'),
            preserve_default=False,
        ),
    ]
