# Generated by Django 2.1.1 on 2019-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0045_estatususuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recado',
            name='asunto',
            field=models.CharField(default='titulo', max_length=150),
            preserve_default=False,
        ),
    ]
