# Generated by Django 2.1.1 on 2019-02-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_auto_20190208_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionriesgo',
            name='tipificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tipificacion'),
            preserve_default=False,
        ),
    ]
