# Generated by Django 2.1.1 on 2019-02-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0048_recomendacionriesgo_tipificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recado',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
