# Generated by Django 2.1.1 on 2019-02-27 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0049_auto_20190215_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField(max_length=2048)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('completado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pendiente',
                'managed': True,
            },
        ),
    ]
