# Generated by Django 2.1.1 on 2019-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0050_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendiente',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
