# Generated by Django 2.1.1 on 2019-03-04 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0051_auto_20190227_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('convenio', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=512)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.AcudeInstitucion')),
            ],
            options={
                'managed': True,
                'db_table': 'sucursal',
            },
        ),
    ]
