# Generated by Django 2.1.1 on 2019-03-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0054_acudeinstitucion_estatus_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='estatus_institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusInstitucion'),
            preserve_default=False,
        ),
    ]
