# Generated by Django 2.1.1 on 2019-03-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0055_sucursal_estatus_institucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipificacionllamada',
            name='descripcion',
        ),
    ]
