# Generated by Django 2.1.1 on 2019-03-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0056_remove_tipificacionllamada_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='devolver_llamada',
            field=models.BooleanField(default=False),
        ),
    ]
