# Generated by Django 2.1.1 on 2019-03-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0057_llamada_devolver_llamada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llamada',
            old_name='a',
            new_name='intervencion',
        ),
        migrations.RenameField(
            model_name='llamada',
            old_name='d',
            new_name='recursos',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='o',
        ),
    ]
