# Generated by Django 2.1.1 on 2019-04-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_aliado_lineanegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaCanalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.AcudeInstitucion')),
            ],
            options={
                'managed': True,
                'db_table': 'llamada_has_canalizaciones',
            },
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='institucion',
        ),
        migrations.AddField(
            model_name='llamada',
            name='aliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Aliado'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='amenazas',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='llamada',
            name='debilidades',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='llamada',
            name='linea_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.LineaNegocio'),
        ),
        migrations.AddField(
            model_name='victima',
            name='num_hijos_mayores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victima',
            name='num_hijos_menores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llamadacanalizacion',
            name='llamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada'),
        ),
    ]
