# Generated by Django 2.1.1 on 2019-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0064_auto_20190410_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='num_hijos_mayores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='victima',
            name='num_hijos_menores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
