# Generated by Django 2.1.1 on 2019-04-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0065_auto_20190410_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaTipificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.CategoriaTipificacion')),
            ],
            options={
                'db_table': 'subcategoria_tipificacion',
                'managed': True,
            },
        ),
    ]
