# Generated by Django 2.1.1 on 2019-04-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0066_subcategoriatipificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipificacionllamada',
            name='subcategoria_tipificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.SubcategoriaTipificacion'),
        ),
    ]
