# Generated by Django 2.1.1 on 2019-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0067_tipificacionllamada_subcategoria_tipificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayuda',
            name='tipo_ayuda',
        ),
        migrations.RemoveField(
            model_name='llamadaayuda',
            name='ayuda',
        ),
        migrations.RemoveField(
            model_name='llamadaayuda',
            name='llamada',
        ),
        migrations.DeleteModel(
            name='TipoCaso',
        ),
        migrations.DeleteModel(
            name='Ayuda',
        ),
        migrations.DeleteModel(
            name='LLamadaAyuda',
        ),
        migrations.DeleteModel(
            name='TipoAyuda',
        ),
    ]
