# Generated by Django 2.1.1 on 2019-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0068_auto_20190426_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, db_column='foto', null=True, upload_to='usuarios/'),
        ),
    ]
