# Generated by Django 2.1.1 on 2019-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0069_auto_20190426_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamada',
            name='tipo_ayuda',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='tipo_caso',
        ),
    ]
