# Generated by Django 2.1.1 on 2019-04-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0070_auto_20190426_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamada',
            name='causa_riesgo',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='fase_violencia',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='semaforo',
        ),
        migrations.DeleteModel(
            name='EstatusLLamada',
        ),
        migrations.DeleteModel(
            name='FaseViolencia',
        ),
        migrations.DeleteModel(
            name='Semaforo',
        ),
    ]
