# Generated by Django 2.1.1 on 2019-05-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0072_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimaMenorEdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('registro', models.BooleanField(default=False)),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tutor')),
            ],
            options={
                'db_table': 'victima_menor_edad',
                'managed': True,
            },
        ),
    ]
