# Generated by Django 2.1.1 on 2019-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0072_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='duracion_minutos',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
