# Generated by Django 2.1.1 on 2019-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0073_llamada_duracion_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llamada',
            name='transferencia',
            field=models.BooleanField(default=False),
        ),
    ]
