# Generated by Django 2.1.1 on 2019-05-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0073_victimamenoredad'),
        ('config', '0074_auto_20190507_2122'),
    ]

    operations = [
    ]
