# Generated by Django 2.1.1 on 2019-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0075_merge_20190513_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='duracion_minutos',
            field=models.TimeField(),
        ),
    ]
