# Generated by Django 2.1.1 on 2019-05-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0078_evaluacion_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='victima',
            name='comentarios_estatus',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='victima',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
