# Generated by Django 2.1.1 on 2019-05-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0078_colonia_cpcolonia'),
        ('config', '0079_auto_20190514_1438'),
    ]

    operations = [
    ]
