# Generated by Django 2.1.1 on 2019-05-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0080_merge_20190517_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpcolonia',
            name='colonia',
        ),
        migrations.DeleteModel(
            name='CPColonia',
        ),
    ]
