# Generated by Django 2.1.1 on 2019-05-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0081_auto_20190517_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPColonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Colonia')),
            ],
            options={
                'managed': True,
                'db_table': 'cp_colonia',
            },
        ),
    ]
