# Generated by Django 2.1.1 on 2019-05-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0083_catcolonias_catestados_catmunicipios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcolonias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='catestados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='catmunicipios',
            options={'managed': True},
        ),
    ]
