# Generated by Django 2.1.1 on 2019-05-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0084_auto_20190528_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcolonias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmunicipios',
            options={'managed': False},
        ),
    ]
