# Generated by Django 2.1.1 on 2019-05-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0086_auto_20190528_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catcolonias',
            name='idcolonia',
        ),
        migrations.RemoveField(
            model_name='catcolonias',
            name='idestado',
        ),
        migrations.RemoveField(
            model_name='catcolonias',
            name='idmunicipio',
        ),
        migrations.RemoveField(
            model_name='catestados',
            name='idestado',
        ),
        migrations.RemoveField(
            model_name='catmunicipios',
            name='idestado',
        ),
        migrations.RemoveField(
            model_name='catmunicipios',
            name='idmun',
        ),
        migrations.AddField(
            model_name='catcolonias',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Catestados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catcolonias',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Catmunicipios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catmunicipios',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Catestados'),
            preserve_default=False,
        ),
    ]
