# Generated by Django 2.1.1 on 2019-05-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0087_auto_20190528_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='catestados',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Pais'),
            preserve_default=False,
        ),
    ]
