# Generated by Django 2.1.1 on 2019-05-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0088_catestados_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='catmunicipios',
            name='idestado',
            field=models.ForeignKey(db_column='idEstado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Catestados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catmunicipios',
            name='idmun',
            field=models.IntegerField(db_column='idMun', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='catmunicipios',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='catmunicipios',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='catmunicipios',
            unique_together={('idmun', 'idestado')},
        ),
    ]
