# Generated by Django 2.1.1 on 2019-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0089_auto_20190528_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcolonias',
            name='cpostal',
            field=models.CharField(db_column='cPostal', max_length=5),
        ),
        migrations.AlterField(
            model_name='catcolonias',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catestados',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='catmunicipios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
