# Generated by Django 2.2.1 on 2019-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0091_auto_20190528_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='catmunicipios',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catcolonias',
            name='municipio',
            field=models.IntegerField(db_column='municipio_id'),
        ),
        migrations.AlterField(
            model_name='catmunicipios',
            name='idestado',
            field=models.IntegerField(db_column='idEstado'),
        ),
        migrations.AlterField(
            model_name='catmunicipios',
            name='idmun',
            field=models.IntegerField(db_column='idMun'),
        ),
        migrations.AlterUniqueTogether(
            name='catmunicipios',
            unique_together=set(),
        ),
    ]
