# Generated by Django 2.2.1 on 2019-05-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0092_auto_20190529_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmunicipios',
            name='id',
        ),
        migrations.AlterField(
            model_name='catcolonias',
            name='municipio',
            field=models.ForeignKey(db_column='municipio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='config.Catmunicipios'),
        ),
        migrations.AlterField(
            model_name='catmunicipios',
            name='idestado',
            field=models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='config.Catestados'),
        ),
        migrations.AlterField(
            model_name='catmunicipios',
            name='idmun',
            field=models.IntegerField(db_column='idMun', primary_key=True, serialize=False),
        )
    ]
