# Generated by Django 2.2.1 on 2019-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0093_auto_20190529_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='palabras_clave',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
