# Generated by Django 2.2.1 on 2019-05-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0094_sucursal_palabras_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamadacanalizacion',
            name='institucion',
        ),
    ]
