# Generated by Django 2.2.1 on 2019-05-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0095_remove_llamadacanalizacion_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadacanalizacion',
            name='sucursal',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Sucursal'),
            preserve_default=False,
        ),
    ]
