# Generated by Django 2.2.1 on 2019-05-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0096_llamadacanalizacion_sucursal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamenMental',
        ),
    ]
