# Generated by Django 2.2.1 on 2019-05-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0097_delete_examenmental'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaExamenMental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categoria_examen_mental',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamenMental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'examen_mental',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamenMentalLLamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_examen_mental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.CategoriaExamenMental')),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Llamada')),
            ],
            options={
                'db_table': 'examen_mental_llamada',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='categoriaexamenmental',
            name='examen_mental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.ExamenMental'),
        ),
    ]
