# Generated by Django 2.1.8 on 2019-06-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0098_auto_20190531_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaexamenmental',
            name='examen_mental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoria_examen', to='config.ExamenMental'),
        ),
    ]
