# Generated by Django 2.1.8 on 2019-06-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0099_auto_20190603_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catcolonias',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='catcolonias',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='catestados',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='catmunicipios',
            name='idestado',
        ),
        migrations.RemoveField(
            model_name='cpcolonia',
            name='colonia',
        ),
        migrations.AddField(
            model_name='colonia',
            name='cp',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='cat_mun_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Catcolonias',
        ),
        migrations.DeleteModel(
            name='Catestados',
        ),
        migrations.DeleteModel(
            name='Catmunicipios',
        ),
        migrations.DeleteModel(
            name='CPColonia',
        ),
    ]
