# Generated by Django 2.1.8 on 2019-06-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0100_auto_20190603_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victima',
            name='colonia',
        ),
    ]
