# Generated by Django 2.1.8 on 2019-06-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0102_victima_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Estado'),
            preserve_default=False,
        ),
    ]
