# Generated by Django 2.2.1 on 2019-06-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0103_sucursal_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='horarios',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefonos',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
