# Generated by Django 2.2.1 on 2019-06-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0104_auto_20190610_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoMental',
        ),
    ]
