# Generated by Django 2.2.1 on 2019-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0105_delete_estadomental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='duracion_servicio',
            field=models.BigIntegerField(),
        ),
    ]
